rover:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  left_wheel:
    type: velocity_controllers/JointVelocityController
    joint: holder2wheel_left
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_wheel:
    type: velocity_controllers/JointVelocityController
    joint: holder2wheel_right
    pid: {p: 100.0, i: 0.01, d: 10.0}
